---
title: "Some quarto notes"
date: 9/28/22
toc: true
highlight-style: pygments
format: 
  html: 
    code-fold: true
    html-math-method: katex
  pdf: 
    geometry: 
      - top=30mm
      - left=20mm
  docx: default
---

## Colors

- Red
- Green 
- Blue

## Shapes

- Square
- Circle
- Triangle

## Textures

- Smooth
- Bumpy
- Fuzzy

## Physics 

Einstein's theory of special relatively that expresses the equivalence of mass and energy: $E = mc^{2}$. See @eq-stddev to better understand standard deviation.

better understand standard better understand standard better understand standard better understand standard better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 
better understand standard better understand standard better understand standard better understand standard 

Even more so: 

$$
4x + 5 = 6 
$$ {#eq-stddev}

w. Like wow!wmqwldqwwe



And wow! Even add callout: 

::: {.callout-note}
Note that there are five types of callouts, including:
`note`, `tip`, `warning`, `caution`, and `important`. Some math $4$ involved:
$$
4x+3=2 
\\ 
4x=-1
\\
x=\frac{-1}{4}
$$

And some `code`: 
```python
print(5)
```
:::



Oh how cool. 

## Rendering code 

w. s

m. [This is awspan that has the class aside which places it in the margin without a footnote number.]{.aside}


wljekw

ns
qmnmwne,mqw
qwkjdklqwkdqk. s
qmnmwne,mqw
qwkjdklqwkdqk. s
qmnmwne,mqw
qwkjdklqwkdqk. sqwdl,mqwqwdl,mqw
qmnmwne,mqw
qwkjdklqwkdqk. s
qmnmwne,mqw
qwkjdklqwkdqk. s
qmnmwne,mqw
qwkjdklqwkdqk. s
qmnmwne,mqw
qwkjdklqwkdqk. s
qmnmwne,mqw
qwkjdklqwkdqk. s
qmnmwne,mqw
qwkjdklqwkdqk. s
qmnmwne,mqw
qwkjdklqwkdqk. s
qmnmwne,mqw
qwkjdklqwkdqk. 